### ISSUE TITLE
Display Presence of Vehicle in Homebridge

### ISSUE THREAD

**Issue by aaronrothschild** [OpenGarage/homebridge-og#8]
It would be great if the plugin could also show the state of the "parking spot" ...present or empty.   Not sure how it could be displayed as an icon in HKit, but this would be a great use of the functionality built into the hardware.

**Comment by csupi003** [comment]
That would be really great to see. I think a homekit occupancy sensor would be possible to show the vehicle.

**Comment by gondalez** [comment]
Great idea @csupi003! 
Parking and leaving could then trigger automations 🏆

**Comment by timcharper** [comment]
Sadly the occupancy of a vehicle is unknown depending on the garage door

I question the utility of having a "maybe" state for the car presence

Personally, I installed a camera in my garage because it's a good idea to be able to visually confirm that it is shut, and, when triggering a remote close, that nothing is under the garage (kids aren't playing around it, etc.)

**Comment by csupi003** [comment]
Looks like the new fw will support ultrasonic sensor for car detection and magnetic for the door at the same time. With this you can place the ultrasonic where it only triggers for cars.
